apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      containers:
        - name: budget-app
          image: tchatotomeko/budget-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb-service:3306/gestion_budget_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.mariadb.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: DEBUG
            - name: LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER
              value: TRACE
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MariaDBDialect
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS
              value: "true"
